// <auto-generated />
using System;
using Blog.Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Blog.Infrastructure.Migrations
{
    [DbContext(typeof(BlogContext))]
    partial class BlogContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Blog.Entities.Concrete.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Blogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 4,
                            Content = "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Architecto, rerum aliquid? Quam culpa quis inventore recusandae itaque. Quo quas tempora, voluptatibus ab, sunt quis ex quasi fugiat iusto modi explicabo quos rerum consequatur quibusdam fuga laborum iure nam architecto. Placeat qui hic porro suscipit voluptate. Placeat aliquid animi delectus perspiciatis quidem, quo illum nihil obcaecati quisquam, modi, eius unde impedit deleniti sunt eligendi voluptates reprehenderit. Nihil incidunt dolor blanditiis sequi illum, neque molestias quidem laborum dolore ea ipsam at culpa inventore facilis aperiam impedit quo nostrum atque architecto accusamus. Optio praesentium impedit eveniet deleniti atque amet aperiam ab, recusandae quaerat nihil culpa magnam eligendi sapiente ea fugit, accusantium temporibus voluptates dolorum sit aut est. Dolore dolores, consequuntur minus ipsa, eos exercitationem similique quibusdam quos inventore earum maxime molestiae, id ut omnis blanditiis alias sunt totam ad ex consequatur assumenda nihil excepturi dolorum? Molestias at, blanditiis magni libero neque recusandae suscipit voluptatem quibusdam delectus impedit earum illo reprehenderit eligendi quasi labore laudantium iure nam similique quis eum velit. Soluta unde odio explicabo est vel. Quo placeat culpa accusantium similique voluptas aliquam libero nisi saepe vero, iusto totam tenetur pariatur facere commodi, necessitatibus explicabo sapiente fugit hic quisquam modi! Nisi, impedit voluptatibus.",
                            CreateDate = new DateTime(2023, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "/web/images/5.jpg",
                            Status = true,
                            Title = "İphone 15 Tanıtıldı",
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 3,
                            Content = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore, iusto reprehenderit quisquam officiis quae illo ab facere veniam, commodi consequatur corrupti aut a suscipit, nam omnis? Dolor, totam! Esse, eveniet expedita in amet necessitatibus dignissimos, asperiores optio adipisci sapiente obcaecati nam? Enim numquam soluta voluptas, ducimus ab nobis consequatur. Cumque eaque expedita voluptates minima, nostrum laborum itaque obcaecati delectus aliquam officiis illo, repudiandae alias sapiente. Ullam culpa libero perferendis id praesentium nemo autem odit illum totam! Totam quae natus aliquid sunt? Illo, at sed? Ab, id? Ut culpa eaque, in deserunt dicta corporis animi numquam repudiandae porro libero totam amet tempore non ducimus odio hic fugit! Nobis consectetur quibusdam ullam velit sapiente praesentium aspernatur voluptates omnis voluptas delectus nam quisquam magni deserunt, cumque impedit, totam quae atque optio officia esse facilis! Fuga, veritatis obcaecati. Omnis, nulla natus! Ipsam, blanditiis autem excepturi, ullam ducimus ut eligendi officiis aperiam ipsum numquam laborum sapiente doloremque consequatur placeat voluptatum quisquam at saepe dolores iure maiores. Dignissimos eos atque eligendi impedit itaque eveniet cum id quod tenetur quam illo soluta optio nihil maxime, corrupti alias fugit iusto unde officia repellat. Deleniti, veniam! Quod sed vitae rem blanditiis similique unde molestias dignissimos nisi possimus. Eum, itaque?",
                            CreateDate = new DateTime(2021, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "/web/images/2.jpg",
                            Status = true,
                            Title = "Kimyager: Walter White",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Content = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni quos harum in! Deserunt dicta dolore, ea vero eos fugit expedita voluptatum eius pariatur error assumenda nihil, illo quaerat a alias, obcaecati animi quibusdam quam consectetur quisquam fugiat? Sequi quas eos temporibus officiis excepturi sunt vero praesentium id quibusdam! Officiis ab repellat inventore qui enim quae ipsum consequuntur, temporibus harum culpa maxime est doloribus provident a magnam unde at saepe nostrum similique eaque corrupti adipisci dolor amet commodi! Atque id aspernatur impedit molestiae autem? Impedit rerum inventore molestiae ipsa similique aliquam iste amet debitis placeat! Fugit praesentium eligendi officiis ullam, sint distinctio, neque ratione maiores consequatur in, quasi facilis nesciunt dolorem. Fugiat quibusdam harum impedit tempore ipsa, tenetur ipsum id deleniti?",
                            CreateDate = new DateTime(2022, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "/web/images/3.jpg",
                            Status = true,
                            Title = "Fifa 2024 Ekim Sonunda Çıkıyor",
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            Content = "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Iure corporis quasi sunt exercitationem, consequatur, optio dolores eum totam omnis nesciunt dolor veniam repudiandae atque alias veritatis iusto? Odit voluptatibus sapiente aliquid. Dicta dolores possimus harum voluptas iusto labore, mollitia atque alias id debitis dignissimos in cum illo corrupti! Doloremque quod, necessitatibus ducimus saepe optio iusto possimus quasi at sed magnam fuga perspiciatis beatae vero modi recusandae fugit! Saepe doloremque veritatis accusamus exercitationem a consequuntur natus aliquam, provident impedit iste modi nam corporis quidem minus, earum magni nesciunt, illo facere molestias dolor alias maiores! Tenetur dolores architecto numquam fugiat voluptates fugit. Rem eligendi explicabo aliquid corporis recusandae repellendus magni sit voluptatem necessitatibus quas magnam consectetur cumque accusamus placeat, ratione similique sed accusantium cum beatae, adipisci fugit nobis excepturi perferendis! Suscipit nam eius cum voluptate impedit, repudiandae, laudantium explicabo nisi molestiae eos fugiat cupiditate. Ipsam cupiditate quidem quo in cum, soluta et dolores repellendus porro ut nesciunt odit quasi necessitatibus maiores! Praesentium dolorum, doloribus porro odit laboriosam repellat. Aperiam quas hic optio provident rerum nostrum facere sit commodi eum alias, atque neque.",
                            CreateDate = new DateTime(2022, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "/web/images/1.jpg",
                            Status = true,
                            Title = "Into The Night",
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Content = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque voluptatibus temporibus numquam iure minima quam animi sit, laudantium quia fugit ea error. Nemo itaque repellendus placeat reiciendis voluptates rerum quidem voluptatibus autem a dicta voluptas, ratione quod repellat corrupti eum veniam inventore illo natus qui animi! Id minima a temporibus voluptas modi aperiam dolore, aliquid non sapiente ullam rem nobis, repudiandae magnam qui aspernatur, quibusdam nemo saepe. Sunt exercitationem aliquid nihil ducimus vitae quam soluta, eveniet neque aspernatur praesentium aut officiis quidem totam impedit, sint voluptatem earum, veritatis cum voluptates atque iure? Quisquam vero esse nostrum architecto. Molestias soluta neque voluptas voluptates rerum velit laudantium ex in odio consectetur aut amet possimus culpa commodi natus quibusdam nam maxime tempore eveniet, nostrum cupiditate aperiam eaque. Culpa temporibus placeat officiis architecto voluptatem illo ex nam consequuntur illum fugiat nihil similique officia quidem exercitationem sapiente, tenetur minus! Labore hic, aut rem ea aspernatur nulla, magni a quaerat cupiditate laudantium error autem velit mollitia perspiciatis beatae dolor assumenda, maiores possimus voluptatibus quisquam accusamus quo doloribus alias corporis. Ex dignissimos aperiam eos qui ut sequi vel illo, voluptate voluptas ullam iste reiciendis? Tenetur at voluptas laboriosam ad dolor. Quidem id unde nemo sint consectetur consequuntur laudantium incidunt. Sit porro odio dolorum quaerat assumenda modi quo molestias vero hic, voluptas molestiae iusto quos? Facere, reiciendis a fugit architecto libero, cumque, perspiciatis reprehenderit hic earum dolor pariatur dolorem! Quia expedita architecto maxime ea fuga veritatis eius ratione. Neque quas beatae porro excepturi veniam! Ipsum dolore voluptas rerum.",
                            CreateDate = new DateTime(2021, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "/web/images/8.jpg",
                            Status = true,
                            Title = "Pyhton ile Veri Analizi",
                            UserId = 3
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Content = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus porro perspiciatis, fugiat qui vel voluptatibus voluptatum molestias harum expedita quasi. Odit facere, iste excepturi qui exercitationem maxime numquam dolores, aperiam error provident commodi. Neque beatae alias necessitatibus perspiciatis aliquam molestias accusantium odio nam cumque ad ipsa, incidunt fuga quisquam. Asperiores minima tempore molestiae itaque voluptate officiis dolorum similique quas excepturi, repellat animi aliquid magni sint tempora earum amet? Dolores laudantium atque velit est corrupti dolore, vel possimus accusamus nemo, quisquam tempore repellendus id. Ducimus dolores dolor accusantium repudiandae nam esse corporis iusto vitae iure exercitationem quasi error voluptas eveniet autem sit dolorum facere, ipsa neque quaerat ipsum at rerum cum. Accusamus exercitationem harum omnis in officiis ullam quaerat. Sint necessitatibus nam illum quo neque mollitia dolores delectus, molestiae, unde doloribus ea eos inventore incidunt, quam iste magnam porro fuga a numquam assumenda? Ullam nihil illo praesentium esse facere sint. Animi dolore laudantium iste facere nobis fugit nostrum assumenda itaque praesentium. Nihil voluptate ea voluptatum, suscipit veritatis cupiditate quam vitae rem dolores omnis animi consequuntur ad magni maiores! Totam distinctio omnis saepe sunt enim ex dolorem, laborum, mollitia deleniti ducimus qui cupiditate doloribus quam architecto velit ut a, ab quisquam optio? Accusamus, ipsam eligendi. Accusantium aspernatur sit quas nemo explicabo magnam aliquam odit quisquam quasi quia odio tempore, molestiae labore est rerum mollitia dicta maxime alias perferendis soluta ratione. Earum, tempore?",
                            CreateDate = new DateTime(2023, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "/web/images/6.jpg",
                            Status = true,
                            Title = "C# ile Asenkron Metodlar",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Blog.Entities.Concrete.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Yazılım",
                            Status = true
                        },
                        new
                        {
                            Id = 2,
                            Name = "Oyun",
                            Status = true
                        },
                        new
                        {
                            Id = 3,
                            Name = "Film",
                            Status = true
                        },
                        new
                        {
                            Id = 4,
                            Name = "Teknoloji",
                            Status = true
                        });
                });

            modelBuilder.Entity("Blog.Entities.Concrete.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BlogId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BlogId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BlogId = 4,
                            Content = "Illo, adipisci! Illo, adipisci!",
                            Date = new DateTime(2023, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = true,
                            Title = "Quisquam vero esse nostrum",
                            UserName = "Ali Yıldırım"
                        },
                        new
                        {
                            Id = 2,
                            BlogId = 3,
                            Content = "Lorem ipsum dolor sit, amet consectetur.",
                            Date = new DateTime(2022, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = true,
                            Title = "voluptas modi aperiam dolore",
                            UserName = "Gizem Çınar"
                        },
                        new
                        {
                            Id = 3,
                            BlogId = 2,
                            Content = "Lorem ipsum dolor sit, amet consectetur. ipsum dolor sit.",
                            Date = new DateTime(2023, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = true,
                            Title = "magnam qui aspernatur",
                            UserName = "Aslı Yıldız"
                        },
                        new
                        {
                            Id = 4,
                            BlogId = 6,
                            Content = "Lorem ipsum dolor sit, amet consectetur.",
                            Date = new DateTime(2023, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = true,
                            Title = "Quisquam vero esse nostrum",
                            UserName = "Mert Kaya"
                        });
                });

            modelBuilder.Entity("Blog.Entities.Concrete.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("Blog.Entities.Concrete.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("int");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2023, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Lorem ipsum dolor sit amet.",
                            ReceiverId = 1,
                            SenderId = 2,
                            Status = true,
                            Subject = "ipsum"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2023, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores, quod.",
                            ReceiverId = 1,
                            SenderId = 3,
                            Status = true,
                            Subject = "ipsum"
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2023, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Similique dolorem laboriosam culpa nisi?",
                            ReceiverId = 2,
                            SenderId = 1,
                            Status = true,
                            Subject = "Similique"
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2023, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "ullam dolorem natus, incidunt ad dolore iste culpa sapiente numquam.",
                            ReceiverId = 3,
                            SenderId = 1,
                            Status = true,
                            Subject = "ullam"
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2023, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores, quod.",
                            ReceiverId = 1,
                            SenderId = 2,
                            Status = true,
                            Subject = "Lorem"
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2023, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Lorem ipsum dolor consectetur adipisicing elit. sit amet consectetur adipisicing elit. Dolores, quod.",
                            ReceiverId = 1,
                            SenderId = 2,
                            Status = true,
                            Subject = "aliquid"
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Lorem ipsum dolorametet modi aliquid maxime placeat architecto. odio quae enim! sit amet consectetur adipisicing elit. Dolores, quod.",
                            ReceiverId = 3,
                            SenderId = 1,
                            Status = true,
                            Subject = "consectetur"
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTime(2023, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores, amet odio quae enim quod.",
                            ReceiverId = 4,
                            SenderId = 2,
                            Status = true,
                            Subject = "Lorem"
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateTime(2023, 7, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Lorem ipsum dolor sit amet consectetur amet odio quae enim adipisicing elit. Dolores, quod.",
                            ReceiverId = 3,
                            SenderId = 2,
                            Status = true,
                            Subject = "aliquid"
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Lorem ipsum doloret modi aliquid maxime placeat architecto. sit amet consectetur adipisicing elit. Dolores, quod.",
                            ReceiverId = 4,
                            SenderId = 2,
                            Status = true,
                            Subject = "doloret"
                        });
                });

            modelBuilder.Entity("Blog.Entities.Concrete.NewsLetter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("NewsLetters");
                });

            modelBuilder.Entity("Blog.Entities.Concrete.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeSymbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Notifications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "preview-icon bg-success",
                            Date = new DateTime(2022, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Lorem ipsum dolor consectetur adipisicing elit.",
                            Status = true,
                            Type = "Günük Toplantı",
                            TypeSymbol = "mdi mdi-calendar"
                        },
                        new
                        {
                            Id = 2,
                            Color = "preview-icon bg-warning",
                            Date = new DateTime(2023, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Lorem ipsum dolor sit, amet consectetur adipisicing elit.Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
                            Status = true,
                            Type = "Doğum Günü",
                            TypeSymbol = "mdi mdi-settings"
                        },
                        new
                        {
                            Id = 3,
                            Color = "preview-icon bg-info",
                            Date = new DateTime(2023, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Illo, adipisci!",
                            Status = true,
                            Type = "Sistem Bakımı",
                            TypeSymbol = "mdi mdi-link-variant"
                        },
                        new
                        {
                            Id = 4,
                            Color = "preview-icon bg-primary",
                            Date = new DateTime(2023, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Illo, adipisci!",
                            Status = true,
                            Type = "Yeni Yazı",
                            TypeSymbol = "mdi mdi-apple"
                        });
                });

            modelBuilder.Entity("Blog.Entities.Concrete.User.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Writer",
                            NormalizedName = "WRITER"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Member",
                            NormalizedName = "MEMBER"
                        });
                });

            modelBuilder.Entity("Blog.Entities.Concrete.User.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("About")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NameSurname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            About = "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Illo, adipisci!",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e5bdb296-fc68-43e7-bf90-74349bdce6cc",
                            Email = "bahadirhakanozturk@blog.com",
                            EmailConfirmed = true,
                            ImageUrl = "/Admin/img/a1.jpg",
                            LockoutEnabled = true,
                            NameSurname = "Bahadır Hakan Öztürk",
                            NormalizedEmail = "BAHADIRHAKANOZTURK@BLOG.COM",
                            NormalizedUserName = "BAHADIRHAKANOZTURK",
                            PasswordHash = "AQAAAAIAAYagAAAAEAcAQO9c+vNbz0xyXf8YOWTZIzq0J9ZOc5bFIVDm8kh8ankLxq16ZVYEH4YJcGWk6A==",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "D2C7BG653KANTFOB6NNHCOSN2R7GM27B",
                            Title = ".Net Geliştiricisi",
                            TwoFactorEnabled = false,
                            UserName = "bahadirhakanozturk"
                        },
                        new
                        {
                            Id = 2,
                            About = "Lorem ipsum dolor sit, amet Lorem ipsum dolor sit, amet consectetur adipisicing consectetur adipisicing elit. Illo, adipisci!",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "15b4e915-cc9a-4102-9250-782262ac0eea",
                            Email = "elifbetulozturk@blog.com",
                            EmailConfirmed = true,
                            ImageUrl = "/web/images/t2.jpg",
                            LockoutEnabled = true,
                            NameSurname = "Elif Betül Öztürk",
                            NormalizedEmail = "ELIFBETULOZTURK@BLOG.COM",
                            NormalizedUserName = "ELIFBETULOZTURK",
                            PasswordHash = "AQAAAAIAAYagAAAAENV76wX++TU3XAZ6RIm/AT0bSSQTtEfbB6HlgjxgdfcqSMGx+o5git5x5iF7gfvmbA==",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "D2C7BG653KANTFOB6NNHCOSN2R7GM27A",
                            Title = "Yazılım Geliştiricisi",
                            TwoFactorEnabled = false,
                            UserName = "elifbetulozturk"
                        },
                        new
                        {
                            Id = 3,
                            About = "Lorem ipsum dolor consectetur adipisicing elit.  sit, amet consectetur adipisicing elit. Illo, adipisci!",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3b2814ae-2b37-42cd-9c70-992a983f9da7",
                            Email = "cemkaya@blog.com",
                            EmailConfirmed = true,
                            ImageUrl = "/web/images/t3.jpg",
                            LockoutEnabled = true,
                            NameSurname = "Cem Kaya",
                            NormalizedEmail = "CEMKAYA@BLOG.COM",
                            NormalizedUserName = "CEMKAYA",
                            PasswordHash = "AQAAAAIAAYagAAAAEEmeoUTVcdEes82Ob2DhNneppgvfJfJwiLfjABmcHvnusxwSC/XbkPm4784GdXu2Mw==",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "D2C7BG653KANTFOB6NNHCOSN2R7GM27C",
                            Title = "Yazar",
                            TwoFactorEnabled = false,
                            UserName = "cemkaya"
                        },
                        new
                        {
                            Id = 4,
                            About = "Lorem ipsum dolor sit, Lorem ipsum dolor sit, amet consectetur adipisicing elit. Illo, adipisci!",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1c5f14f9-585c-49a0-9ce0-72aa330e2f10",
                            Email = "aysecinar@blog.com",
                            EmailConfirmed = true,
                            ImageUrl = "/web/images/t4.jpg",
                            LockoutEnabled = true,
                            NameSurname = "Ayşe Çınar",
                            NormalizedEmail = "AYSECINAR@BLOG.COM",
                            NormalizedUserName = "AYSECINAR",
                            PasswordHash = "AQAAAAIAAYagAAAAEKLp2DsMwD/L9QCd4sfrIlNDbT5lTsXsf6q5C7PFHMn86g/WEimGN0I1lkAfqCiZOw==",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "D2C7BG653KANTFOB6NNHCOSN2R7GM27D",
                            TwoFactorEnabled = false,
                            UserName = "aysecinar"
                        },
                        new
                        {
                            Id = 5,
                            About = "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Illo, adipisci! Illo, adipisci! Illo, adipisci!",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4eb21eb4-3d42-4b63-b2b9-743c14b43664",
                            Email = "hakkican@blog.com",
                            EmailConfirmed = true,
                            ImageUrl = "/Admin/img/a4.jpg",
                            LockoutEnabled = true,
                            NameSurname = "Hakkı Can",
                            NormalizedEmail = "HAKKICAN@BLOG.COM",
                            NormalizedUserName = "HAKKICAN",
                            PasswordHash = "AQAAAAIAAYagAAAAEEOI0SGNN9Ty6dtFdGSOPpaNKj/VShVJsiYis+n7bWo4aVhCC5Z+41GXGA6pfKoWmg==",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "D2C7BG653KANTFOB6NNHCOSN2R7GM27S",
                            TwoFactorEnabled = false,
                            UserName = "hakkican"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 4,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 5,
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Blog.Entities.Concrete.Blog", b =>
                {
                    b.HasOne("Blog.Entities.Concrete.Category", "Category")
                        .WithMany("Blogs")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Blog.Entities.Concrete.User.AppUser", "User")
                        .WithMany("Blogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Blog.Entities.Concrete.Comment", b =>
                {
                    b.HasOne("Blog.Entities.Concrete.Blog", "Blog")
                        .WithMany("Comments")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blog");
                });

            modelBuilder.Entity("Blog.Entities.Concrete.Message", b =>
                {
                    b.HasOne("Blog.Entities.Concrete.User.AppUser", "Receiver")
                        .WithMany("InboxMessages")
                        .HasForeignKey("ReceiverId")
                        .IsRequired();

                    b.HasOne("Blog.Entities.Concrete.User.AppUser", "Sender")
                        .WithMany("OutboxMessages")
                        .HasForeignKey("SenderId")
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Blog.Entities.Concrete.User.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Blog.Entities.Concrete.User.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Blog.Entities.Concrete.User.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Blog.Entities.Concrete.User.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Blog.Entities.Concrete.User.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Blog.Entities.Concrete.User.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Blog.Entities.Concrete.Blog", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("Blog.Entities.Concrete.Category", b =>
                {
                    b.Navigation("Blogs");
                });

            modelBuilder.Entity("Blog.Entities.Concrete.User.AppUser", b =>
                {
                    b.Navigation("Blogs");

                    b.Navigation("InboxMessages");

                    b.Navigation("OutboxMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
